name: "Publish latest action tag"

on:
  release:
    types: [published, edited]

jobs:
  latest:
    name: Publish latest tag
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸš€ publish action"
        uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
